name: my-awesome-telegram-action

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # every hour
    - cron: '0 * * * *'

# TODO action to deploy hugo on pr merged
jobs:
  telegram-action:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TIMESTAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch latest messages
        run: ${{ github.workspace }}/.github/scripts/telegram.sh
        env:
          DATA_PATH: "./data/telegram.json"
          # add secrets manually
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_FROM_ID: ${{ secrets.TELEGRAM_FROM_ID }}        
      
      - name: Update repository
        run: ${{ github.workspace }}/.github/scripts/update.sh
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
